### ISSUE TITLE
Character Expander not work

### ISSUE THREAD

**Issue by Cava20** [zealottormunds/ns4moddingapi#3]
Hi, i have expanded with HxD the characode.xfbin, but when i launch the game with the api, the game loads eternally.

**Comment by zealottormunds** [comment]
I recommend using this tutorial:
https://www.youtube.com/watch?v=Ll9WmOgJAEk

Sorry for the delay!

**Comment by Cava20** [comment]
Thank you for the reply. You have to know that my first question was answered when i was using your Modding API 1.3c . Now, with the 1.3d , i have a different problem.

I have tested some things, and there is this: it seems that the characode.xfbin file allow to add only one new characode, and with that, the game crash when i select the added character. 
If i add not one, but two new characodes, the game loads eternally like in my first question.
So, with only one new characode added, i tried to swap the characode of a character already in the game with the one added, and then the new character is playable but the old one not.

Finally, i tried to add a character with the old version of the game, the 1.7, with your Modding API 1.2b, and everything works like in the video that you have posted up here.

So... I don't know, it's everything i found XD

Sorry for the trouble!

**Comment by zealottormunds** [comment]
Oooooo that's really strange. I believe the character manager is kinda broken in 1.8 actually, so I updated it to the latest version and I'll be uploading in a few hours. I hope this issue will be fixed with the latest one! I'll let you know when it's uploaded.
